name: test_basic
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  nostra_bdd_steps:
    path: ../nostra_bdd_steps

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.6
  bdd_widget_test: ^1.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/
